---
apiVersion: v1
kind: Service
metadata:
  name: control
  namespace: {{ .Values.appEnv }}-travel-control
  labels:
    app: control
spec:
  ports:
  {{- with $svc := $.Values.service }}
    - name: {{ $svc.name }}
      port: {{ $svc.port }}
  {{- end }}
  selector:
    app: control
