---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: mysqldb-credentials-external-secret
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: mysql-credentials
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: {{ .Values.mysqldbCredentials.key }}
