apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "mysqldb.selectorLabels" . | nindent 4 }}
  name: {{ include "mysqldb.fullname" . }}
spec:
  ports:
  {{- with .Values.service }}
  - name: {{ .name }}
    port: {{ .port }}
    protocol: {{ .protocol }}
    targetPort: {{ default .port .targetPort }}
  {{- end }}
  selector:
    {{- include "mysqldb.selectorLabels" . | nindent 4 }}
