{{- range .Values.members }}
---
apiVersion: maistra.io/v1
kind: ServiceMeshMember
metadata:
  name: default
  namespace: dev-travel-{{ . }}
spec:
  controlPlaneRef:
    name: dev-basic
    namespace: dev-istio-system
{{- end }}