apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: control-gateway
  namespace: {{ .Values.appEnv }}-istio-system
  annotations:
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  servers:
    - hosts:
        - istio-ingressgateway-{{ .Values.appEnv }}-istio-system.{{ .Values.global.localClusterDomain }}
      port:
        name: http
        number: 80
        protocol: HTTP
  selector:
    istio: ingressgateway
