apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: control
  namespace: {{ .Values.appEnv }}-travel-control
  annotations:
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  hosts:
    - istio-ingressgateway-{{ .Values.appEnv }}-istio-system.{{ .Values.global.localClusterDomain }}
  gateways:
    - {{ .Values.appEnv }}-istio-system/control-gateway
  http:
    - route:
        - destination:
            host: control.{{ .Values.appEnv }}-travel-control.svc.cluster.local
            subset: v1
          weight: 100
