{{- range $apps := .Values.apps }}
{{ $version := $.Values.appVersion }}
{{ $env := $.Values.appEnv }}
{{- with $img := $.Values.image }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $apps.name }}
  namespace: {{ $env }}-travel-portal
spec:
  selector:
    matchLabels:
      app: {{ $apps.name }}
      version: {{ $version }}
  replicas: {{ $.Values.replicaCount }}
  template:
    metadata:
      annotations:
      {{- include "travel-portal.istioProxyConfig" . | nindent 8 }}
      labels:
        app: {{ $apps.name }}
        version: {{ $version }}
    spec:
      containers:
        {{- if eq $apps.name "voyages" }}
        - name: {{ $apps.name }}
        {{- else }}
        - name: control
        {{- end }}
          image: {{ $img.registry }}/{{ $img.repository }}/demo_travels_portal:{{ $img.tag }}
          imagePullPolicy: {{ $img.pullPolicy }}
          ports:
            - containerPort: {{ $.Values.service.port }}
          securityContext:
            privileged: false
          env:
          {{- with $apps.env }}
            - name: LISTEN_ADDRESS
              value: ":8000"
            - name: PORTAL_COORDINATES
              value: {{ .coordinates | quote }}
            - name: PORTAL_COUNTRY
              value: {{ .country | quote }}
            - name: PORTAL_NAME
              value: "{{ $apps.name }}.{{ .countryShort }}"
            - name: TRAVELS_AGENCY_SERVICE
              value: "http://travels.{{ $env }}-travel-agency:8000"
          {{- end }}
{{- end }}
{{- end }}
